https://freefrontend.com/tailwind-hero-sections/

https://www.training-dev.fr/Cours/Les-bases-de-Vue.JS-3/Introduction-et-installation
https://tahe.developpez.com/tutoriels-cours/vuejs/
https://openclassrooms.com/fr/courses/6390311-creez-une-application-web-avec-vue-js